"""
Professional Time & Attendance Report PDF Generator

Generates a clean, professional time attendance report PDF with:
- Simple header with company name and metadata
- One page per employee with summary cards, time entries table
- Clean footer with page numbers
"""
from typing import List, Dict
from datetime import datetime, date
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_LEFT, TA_RIGHT, TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, 
    PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
import re


def sanitize_html(text: str) -> str:
    """Sanitize text for ReportLab Paragraph."""
    if not text:
        return ""
    text = str(text)
    text = re.sub(r'<script[^>]*>.*?</script>', '', text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r'&(?!\w+;)', '&amp;', text)
    return text


def capitalize_status(status: str) -> str:
    """Capitalize the first letter of status string."""
    if not status:
        return ""
    status_str = str(status).strip()
    if not status_str:
        return ""
    return status_str[0].upper() + status_str[1:].lower() if len(status_str) > 1 else status_str.upper()


def generate_time_attendance_report_pdf(
    company_name: str,
    period_start: date,
    period_end: date,
    generated_at: datetime,
    generated_by: str,
    employees_data: List[Dict],
) -> bytes:
    """
    Generate professional time attendance report PDF with one page per employee.
    
    Args:
        company_name: Company name
        period_start: Period start date
        period_end: Period end date
        generated_at: Generation timestamp
        generated_by: Name of person who generated report
        employees_data: List of employee data dicts
    
    Returns:
        PDF bytes
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=0.75*inch,
        rightMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch,
    )
    story = []
    styles = getSampleStyleSheet()
    
    # Clean, professional color scheme
    primary_color = colors.HexColor('#1e40af')
    dark_text = colors.HexColor('#1f2937')
    gray_text = colors.HexColor('#6b7280')
    light_gray = colors.HexColor('#f3f4f6')
    border_color = colors.HexColor('#e5e7eb')
    
    # Process each employee - one page per employee
    for emp_idx, emp_data in enumerate(employees_data):
        if emp_idx > 0:
            story.append(PageBreak())
        
        # ========== HEADER ==========
        header_table_data = []
        
        # Company name (left)
        company_style = ParagraphStyle(
            'Company',
            parent=styles['Normal'],
            fontSize=18,
            fontName='Helvetica-Bold',
            textColor=dark_text,
            spaceAfter=8,
            leading=22,
        )
        
        company_cell = [[Paragraph(sanitize_html(company_name), company_style)]]
        
        # Metadata (right)
        meta_style = ParagraphStyle(
            'Meta',
            parent=styles['Normal'],
            fontSize=9,
            textColor=gray_text,
            alignment=TA_RIGHT,
            leading=12,
        )
        
        period_str = f"{period_start.strftime('%b %d, %Y')} - {period_end.strftime('%b %d, %Y')}"
        generated_str = generated_at.strftime('%b %d, %Y at %I:%M %p')
        
        metadata = f"""
        <b>Report Period:</b> {sanitize_html(period_str)}<br/>
        <b>Generated:</b> {sanitize_html(generated_str)}<br/>
        <b>Generated By:</b> {sanitize_html(generated_by)}
        """
        
        header_table_data.append([
            Table(company_cell, colWidths=[4*inch]),
            Paragraph(metadata, meta_style)
        ])
        
        header_table = Table(header_table_data, colWidths=[4*inch, 2.5*inch])
        header_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
        ]))
        
        story.append(header_table)
        story.append(Spacer(1, 0.15*inch))
        
        # Divider line
        divider = Table([['']], colWidths=[6.5*inch], rowHeights=[1])
        divider.setStyle(TableStyle([
            ('LINEBELOW', (0, 0), (-1, -1), 1, border_color),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
        ]))
        story.append(divider)
        story.append(Spacer(1, 0.25*inch))
        
        # Employee name and title
        employee_name = sanitize_html(str(emp_data.get('employee_name', 'Unknown')))
        job_role = sanitize_html(str(emp_data.get('job_role', '')))
        
        employee_style = ParagraphStyle(
            'Employee',
            parent=styles['Normal'],
            fontSize=16,
            fontName='Helvetica-Bold',
            textColor=dark_text,
            spaceAfter=2,
            leading=20,
        )
        
        role_style = ParagraphStyle(
            'Role',
            parent=styles['Normal'],
            fontSize=11,
            fontName='Helvetica',
            textColor=gray_text,
            spaceAfter=16,
            leading=14,
        )
        
        story.append(Paragraph(employee_name, employee_style))
        if job_role:
            story.append(Paragraph(job_role, role_style))
        else:
            story.append(Spacer(1, 14))
        
        # ========== SUMMARY CARDS ==========
        total_entries = emp_data.get('total_entries', 0)
        total_hours = float(emp_data.get('total_hours', 0))
        total_break_minutes = int(emp_data.get('total_break_minutes', 0))
        avg_hours = float(emp_data.get('avg_hours_per_day', 0))
        
        card_number_style = ParagraphStyle(
            'CardNumber',
            parent=styles['Normal'],
            fontSize=20,
            fontName='Helvetica-Bold',
            textColor=primary_color,
            alignment=TA_CENTER,
            spaceAfter=4,
            leading=24,
        )
        card_label_style = ParagraphStyle(
            'CardLabel',
            parent=styles['Normal'],
            fontSize=9,
            textColor=gray_text,
            alignment=TA_CENTER,
            spaceAfter=0,
            fontName='Helvetica',
            leading=11,
        )
        
        summary_cards = Table([
            [
                [Paragraph(f"{total_entries}", card_number_style), Paragraph("Entries", card_label_style)],
                [Paragraph(f"{total_hours:.2f}", card_number_style), Paragraph("Total Hours", card_label_style)],
                [Paragraph(f"{total_break_minutes}", card_number_style), Paragraph("Break (min)", card_label_style)],
                [Paragraph(f"{avg_hours:.2f}", card_number_style), Paragraph("Avg Hours/Day", card_label_style)],
            ]
        ], colWidths=[1.625*inch] * 4)
        
        summary_cards.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.white),
            ('BOX', (0, 0), (-1, -1), 1, border_color),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('TOPPADDING', (0, 0), (-1, -1), 16),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 16),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ]))
        
        story.append(summary_cards)
        story.append(Spacer(1, 0.3*inch))
        
        # ========== TIME ENTRIES TABLE ==========
        entries = emp_data.get('entries', [])
        
        if entries:
            table_data = []
            
            # Header row
            header_style = ParagraphStyle(
                'Header',
                parent=styles['Normal'],
                fontSize=10,
                fontName='Helvetica-Bold',
                textColor=colors.white,
                alignment=TA_CENTER,
                leading=12,
            )
            header_row = ["Date", "Clock In", "Clock Out", "Hours", "Break", "Status"]
            table_data.append([Paragraph(sanitize_html(str(cell)), header_style) for cell in header_row])
            
            # Data rows
            cell_style = ParagraphStyle(
                'Cell',
                parent=styles['Normal'],
                fontSize=9,
                alignment=TA_LEFT,
                fontName='Helvetica',
                leading=11,
                textColor=dark_text,
            )
            cell_style_center = ParagraphStyle(
                'CellCenter',
                parent=styles['Normal'],
                fontSize=9,
                alignment=TA_CENTER,
                fontName='Helvetica',
                leading=11,
                textColor=dark_text,
            )
            cell_style_right = ParagraphStyle(
                'CellRight',
                parent=styles['Normal'],
                fontSize=9,
                alignment=TA_RIGHT,
                fontName='Helvetica',
                leading=11,
                textColor=dark_text,
            )
            
            for entry in entries:
                date_str = sanitize_html(str(entry.get('date', '')))
                clock_in = sanitize_html(str(entry.get('clock_in', '')))
                clock_out = sanitize_html(str(entry.get('clock_out', 'Open')))
                hours = float(entry.get('hours', 0))
                break_minutes = int(entry.get('break_minutes', 0))
                status = sanitize_html(capitalize_status(str(entry.get('status', ''))))
                
                table_data.append([
                    Paragraph(date_str, cell_style),
                    Paragraph(clock_in, cell_style_center),
                    Paragraph(clock_out, cell_style_center),
                    Paragraph(f"{hours:.2f}", cell_style_right),
                    Paragraph(f"{break_minutes}", cell_style_right),
                    Paragraph(status, cell_style_center),
                ])
            
            # Totals row
            totals_style = ParagraphStyle(
                'Totals',
                parent=styles['Normal'],
                fontSize=10,
                fontName='Helvetica-Bold',
                textColor=colors.white,
                alignment=TA_LEFT,
            )
            totals_style_right = ParagraphStyle(
                'TotalsRight',
                parent=styles['Normal'],
                fontSize=10,
                fontName='Helvetica-Bold',
                textColor=colors.white,
                alignment=TA_RIGHT,
            )
            
            table_data.append([
                Paragraph("TOTAL", totals_style),
                Paragraph("", totals_style),
                Paragraph("", totals_style),
                Paragraph(f"{total_hours:.2f}", totals_style_right),
                Paragraph(f"{total_break_minutes}", totals_style_right),
                Paragraph("", totals_style),
            ])
            
            # Create table
            col_widths = [1.3*inch, 1.0*inch, 1.0*inch, 0.9*inch, 0.9*inch, 1.1*inch]
            table = Table(table_data, colWidths=col_widths)
            
            table.setStyle(TableStyle([
                # Header row
                ('BACKGROUND', (0, 0), (-1, 0), primary_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
                ('TOPPADDING', (0, 0), (-1, 0), 10),
                
                # Data rows - alternating background
                ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, light_gray]),
                ('TOPPADDING', (0, 1), (-1, -2), 8),
                ('BOTTOMPADDING', (0, 1), (-1, -2), 8),
                
                # Alignment
                ('ALIGN', (0, 1), (0, -2), 'LEFT'),  # Date
                ('ALIGN', (1, 1), (2, -2), 'CENTER'),  # Clock in/out
                ('ALIGN', (3, 1), (4, -2), 'RIGHT'),  # Hours, Break
                ('ALIGN', (5, 1), (5, -2), 'CENTER'),  # Status
                
                # Totals row
                ('BACKGROUND', (0, -1), (-1, -1), primary_color),
                ('TEXTCOLOR', (0, -1), (-1, -1), colors.white),
                ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, -1), (-1, -1), 10),
                ('TOPPADDING', (0, -1), (-1, -1), 10),
                ('BOTTOMPADDING', (0, -1), (-1, -1), 10),
                ('ALIGN', (0, -1), (2, -1), 'LEFT'),
                ('ALIGN', (3, -1), (4, -1), 'RIGHT'),
                
                # Grid
                ('GRID', (0, 0), (-1, -1), 0.5, border_color),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ]))
            
            story.append(table)
        else:
            # No entries message
            no_entries_style = ParagraphStyle(
                'NoEntries',
                parent=styles['Normal'],
                fontSize=10,
                textColor=gray_text,
                alignment=TA_CENTER,
                spaceAfter=20,
            )
            story.append(Paragraph("No time entries found for this period", no_entries_style))
    
    # ========== FOOTER ==========
    def add_footer(canvas_obj, doc):
        """Add footer with page number."""
        canvas_obj.saveState()
        
        # Page number (centered)
        page_num = canvas_obj.getPageNumber()
        canvas_obj.setFont("Helvetica", 9)
        canvas_obj.setFillColor(gray_text)
        page_text = f"Page {page_num}"
        text_width = canvas_obj.stringWidth(page_text, "Helvetica", 9)
        page_width = doc.pagesize[0]
        canvas_obj.drawString((page_width - text_width) / 2, 0.5 * inch, page_text)
        
        canvas_obj.restoreState()
    
    # Build PDF
    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    buffer.seek(0)
    return buffer.read()
